//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashSys.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cashier
    {
        public Cashier()
        {
            this.Client = new HashSet<Client>();
        }
    
        public int cashier_serial_id { get; set; }
        public string cashier_user_name { get; set; }
        public string cashier_first_name { get; set; }
        public string cashier_last_name { get; set; }
        public string cashier_password { get; set; }
        public Nullable<int> cashier_desk { get; set; }
    
        public virtual ICollection<Client> Client { get; set; }
    }
}
