//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashSys.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class payments
    {
        public payments()
        {
            this.Obligations = new HashSet<Obligations>();
        }
    
        public int payment_id { get; set; }
        public System.DateTime date_of_payment { get; set; }
        public decimal amount_of_payment { get; set; }
    
        public virtual ICollection<Obligations> Obligations { get; set; }
    }
}
